-- MySQL Script generated by MySQL Workbench
-- Thu Aug 13 19:39:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema captain_kai_sod_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema captain_kai_sod_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `captain_kai_sod_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `captain_kai_sod_db` ;

-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`roles` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `uq_roles_role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT UNSIGNED NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `status` ENUM('ACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  `last_login_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `uq_users_username` (`username` ASC) VISIBLE,
  INDEX `fk_users_role` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `captain_kai_sod_db`.`roles` (`role_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`categories` (
  `category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `uq_categories_category_name` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`products` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `supplier_id` INT UNSIGNED NULL DEFAULT NULL,
  `sku` VARCHAR(50) NOT NULL,
  `product_name` VARCHAR(200) NOT NULL,
  `base_unit` VARCHAR(30) NOT NULL COMMENT 'หน่วยฐานสำหรับตัดสต็อก เช่น กิโลกรัม',
  `reorder_point` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `image_url` VARCHAR(500) NULL DEFAULT NULL,
  `image_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `is_active` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `uq_products_sku` (`sku` ASC) VISIBLE,
  INDEX `fk_products_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `captain_kai_sod_db`.`categories` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`product_units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`product_units` (
  `product_unit_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `unit_name` VARCHAR(50) NOT NULL COMMENT 'เช่น กิโลกรัม, ขีด, แพ็ก, ชิ้น',
  `conversion_factor` DECIMAL(14,3) NOT NULL COMMENT 'จำนวนหน่วยฐานต่อ 1 หน่วยขาย',
  `selling_price` DECIMAL(12,2) NOT NULL,
  `barcode` VARCHAR(100) NULL DEFAULT NULL,
  `is_default` TINYINT NOT NULL DEFAULT FALSE,
  `is_active` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`product_unit_id`),
  UNIQUE INDEX `uq_product_units_barcode` (`barcode` ASC) VISIBLE,
  UNIQUE INDEX `uq_product_unit` (`product_id` ASC, `unit_name` ASC) VISIBLE,
  CONSTRAINT `fk_product_units_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `captain_kai_sod_db`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`suppliers` (
  `supplier_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`goods_receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`goods_receipts` (
  `receipt_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supplier_id` INT UNSIGNED NOT NULL,
  `received_by` INT UNSIGNED NOT NULL,
  `receipt_no` VARCHAR(50) NOT NULL,
  `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('DRAFT', 'CONFIRMED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  PRIMARY KEY (`receipt_id`),
  UNIQUE INDEX `uq_goods_receipts_receipt_no` (`receipt_no` ASC) VISIBLE,
  INDEX `fk_goods_receipts_supplier` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_goods_receipts_user` (`received_by` ASC) VISIBLE,
  CONSTRAINT `fk_goods_receipts_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `captain_kai_sod_db`.`suppliers` (`supplier_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_goods_receipts_user`
    FOREIGN KEY (`received_by`)
    REFERENCES `captain_kai_sod_db`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`goods_receipt_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`goods_receipt_items` (
  `receipt_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `receipt_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity_base` DECIMAL(14,3) NOT NULL COMMENT 'จำนวนรับเข้าในหน่วยฐาน',
  `unit_cost` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`receipt_item_id`),
  INDEX `fk_goods_receipt_items_receipt` (`receipt_id` ASC) VISIBLE,
  INDEX `fk_goods_receipt_items_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_goods_receipt_items_receipt`
    FOREIGN KEY (`receipt_id`)
    REFERENCES `captain_kai_sod_db`.`goods_receipts` (`receipt_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_goods_receipt_items_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `captain_kai_sod_db`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`product_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`product_batches` (
  `batch_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `receipt_item_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `lot_no` VARCHAR(100) NOT NULL,
  `received_date` DATE NOT NULL,
  `expiry_date` DATE NULL DEFAULT NULL,
  `quantity_received_base` DECIMAL(14,3) NOT NULL,
  `quantity_remaining_base` DECIMAL(14,3) NOT NULL,
  `status` ENUM('ACTIVE', 'NEAR_EXPIRY', 'EXPIRED', 'DEPLETED') NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`batch_id`),
  UNIQUE INDEX `uq_product_batch` (`product_id` ASC, `lot_no` ASC) VISIBLE,
  INDEX `fk_product_batches_receipt_item` (`receipt_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_batches_receipt_item`
    FOREIGN KEY (`receipt_item_id`)
    REFERENCES `captain_kai_sod_db`.`goods_receipt_items` (`receipt_item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_batches_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `captain_kai_sod_db`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`customers` (
  `customer_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `vehicle_plate` VARCHAR(30) NULL DEFAULT NULL,
  `parking_spot` VARCHAR(100) NULL DEFAULT NULL,
  `credit_limit` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `is_active` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `uq_customers_phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`sales` (
  `sale_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` INT UNSIGNED NULL DEFAULT NULL COMMENT 'ว่างได้ หากเป็นลูกค้าทั่วไป',
  `cashier_id` INT UNSIGNED NOT NULL,
  `sale_no` VARCHAR(50) NOT NULL,
  `sold_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `sale_status` ENUM('COMPLETED', 'CANCELLED', 'CREDIT') NOT NULL DEFAULT 'COMPLETED',
  PRIMARY KEY (`sale_id`),
  UNIQUE INDEX `uq_sales_sale_no` (`sale_no` ASC) VISIBLE,
  INDEX `fk_sales_customer` (`customer_id` ASC) VISIBLE,
  INDEX `fk_sales_cashier` (`cashier_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `captain_kai_sod_db`.`customers` (`customer_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_cashier`
    FOREIGN KEY (`cashier_id`)
    REFERENCES `captain_kai_sod_db`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`sale_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`sale_items` (
  `sale_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sale_id` INT UNSIGNED NOT NULL,
  `product_unit_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(14,3) NOT NULL COMMENT 'จำนวนตามหน่วยขาย',
  `quantity_base` DECIMAL(14,3) NOT NULL COMMENT 'จำนวนที่แปลงเป็นหน่วยฐาน',
  `unit_price` DECIMAL(12,2) NOT NULL COMMENT 'ราคาจริง ณ วันที่ขาย',
  `discount_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `line_total` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`sale_item_id`),
  INDEX `fk_sale_items_sale` (`sale_id` ASC) VISIBLE,
  INDEX `fk_sale_items_product_unit` (`product_unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_items_sale`
    FOREIGN KEY (`sale_id`)
    REFERENCES `captain_kai_sod_db`.`sales` (`sale_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_items_product_unit`
    FOREIGN KEY (`product_unit_id`)
    REFERENCES `captain_kai_sod_db`.`product_units` (`product_unit_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`sale_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`sale_payments` (
  `sale_payment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sale_id` INT UNSIGNED NOT NULL,
  `payment_method` ENUM('CASH', 'QR_CODE', 'BANK_TRANSFER') NOT NULL,
  `paid_amount` DECIMAL(12,2) NOT NULL,
  `change_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `paid_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reference_no` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`sale_payment_id`),
  INDEX `fk_sale_payments_sale` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_payments_sale`
    FOREIGN KEY (`sale_id`)
    REFERENCES `captain_kai_sod_db`.`sales` (`sale_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`credit_invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`credit_invoices` (
  `credit_invoice_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sale_id` INT UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `invoice_no` VARCHAR(50) NOT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `original_amount` DECIMAL(12,2) NOT NULL,
  `outstanding_amount` DECIMAL(12,2) NOT NULL,
  `invoice_status` ENUM('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE') NOT NULL DEFAULT 'UNPAID',
  PRIMARY KEY (`credit_invoice_id`),
  UNIQUE INDEX `uq_credit_invoices_sale_id` (`sale_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_credit_invoices_invoice_no` (`invoice_no` ASC) VISIBLE,
  INDEX `fk_credit_invoices_customer` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_credit_invoices_sale`
    FOREIGN KEY (`sale_id`)
    REFERENCES `captain_kai_sod_db`.`sales` (`sale_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_credit_invoices_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `captain_kai_sod_db`.`customers` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`credit_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`credit_payments` (
  `credit_payment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `credit_invoice_id` INT UNSIGNED NOT NULL,
  `received_by` INT UNSIGNED NOT NULL,
  `paid_amount` DECIMAL(12,2) NOT NULL,
  `payment_method` ENUM('CASH', 'QR_CODE', 'BANK_TRANSFER') NOT NULL,
  `paid_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reference_no` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`credit_payment_id`),
  INDEX `fk_credit_payments_invoice` (`credit_invoice_id` ASC) VISIBLE,
  INDEX `fk_credit_payments_user` (`received_by` ASC) VISIBLE,
  CONSTRAINT `fk_credit_payments_invoice`
    FOREIGN KEY (`credit_invoice_id`)
    REFERENCES `captain_kai_sod_db`.`credit_invoices` (`credit_invoice_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_credit_payments_user`
    FOREIGN KEY (`received_by`)
    REFERENCES `captain_kai_sod_db`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`stock_movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`stock_movements` (
  `movement_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` INT UNSIGNED NOT NULL,
  `recorded_by` INT UNSIGNED NOT NULL,
  `sale_item_id` INT UNSIGNED NULL DEFAULT NULL,
  `movement_type` ENUM('IN', 'OUT', 'ADJUSTMENT', 'EXPIRED') NOT NULL,
  `quantity_base` DECIMAL(14,3) NOT NULL,
  `moved_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reference_no` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`movement_id`),
  INDEX `fk_stock_movements_batch` (`batch_id` ASC) VISIBLE,
  INDEX `fk_stock_movements_user` (`recorded_by` ASC) VISIBLE,
  INDEX `fk_stock_movements_sale_item` (`sale_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_movements_batch`
    FOREIGN KEY (`batch_id`)
    REFERENCES `captain_kai_sod_db`.`product_batches` (`batch_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_movements_user`
    FOREIGN KEY (`recorded_by`)
    REFERENCES `captain_kai_sod_db`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_movements_sale_item`
    FOREIGN KEY (`sale_item_id`)
    REFERENCES `captain_kai_sod_db`.`sale_items` (`sale_item_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`order_recommendations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`order_recommendations` (
  `recommendation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_by` INT UNSIGNED NOT NULL,
  `recommendation_date` DATE NOT NULL,
  `status` ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'DRAFT',
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`recommendation_id`),
  INDEX `fk_order_recommendations_user` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_order_recommendations_user`
    FOREIGN KEY (`created_by`)
    REFERENCES `captain_kai_sod_db`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`order_recommendation_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`order_recommendation_items` (
  `recommendation_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `recommendation_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `suggested_quantity_base` DECIMAL(14,3) NOT NULL,
  `approved_quantity_base` DECIMAL(14,3) NULL DEFAULT NULL,
  `historical_sales_qty_base` DECIMAL(14,3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`recommendation_item_id`),
  INDEX `fk_recommendation_items_recommendation` (`recommendation_id` ASC) VISIBLE,
  INDEX `fk_recommendation_items_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_recommendation_items_recommendation`
    FOREIGN KEY (`recommendation_id`)
    REFERENCES `captain_kai_sod_db`.`order_recommendations` (`recommendation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recommendation_items_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `captain_kai_sod_db`.`products` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`cash_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`cash_categories` (
  `cash_category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `transaction_type` ENUM('INCOME', 'EXPENSE') NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`cash_category_id`),
  UNIQUE INDEX `uq_cash_categories_name` (`category_name` ASC, `transaction_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captain_kai_sod_db`.`cash_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captain_kai_sod_db`.`cash_transactions` (
  `cash_transaction_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cash_category_id` INT UNSIGNED NOT NULL,
  `recorded_by` INT UNSIGNED NOT NULL,
  `sale_payment_id` INT UNSIGNED NULL DEFAULT NULL,
  `credit_payment_id` INT UNSIGNED NULL DEFAULT NULL,
  `transaction_type` ENUM('INCOME', 'EXPENSE') NOT NULL,
  `transaction_date` DATE NOT NULL,
  `transaction_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` DECIMAL(12,2) NOT NULL,
  `payment_method` ENUM('CASH', 'QR_CODE', 'BANK_TRANSFER', 'OTHER') NOT NULL DEFAULT 'CASH',
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `reference_no` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`cash_transaction_id`),
  UNIQUE INDEX `uq_cash_transactions_sale_payment` (`sale_payment_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_cash_transactions_credit_payment` (`credit_payment_id` ASC) VISIBLE,
  INDEX `idx_cash_transactions_date` (`transaction_date` ASC) VISIBLE,
  INDEX `fk_cash_transactions_category` (`cash_category_id` ASC) VISIBLE,
  INDEX `fk_cash_transactions_user` (`recorded_by` ASC) VISIBLE,
  CONSTRAINT `fk_cash_transactions_category`
    FOREIGN KEY (`cash_category_id`)
    REFERENCES `captain_kai_sod_db`.`cash_categories` (`cash_category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cash_transactions_user`
    FOREIGN KEY (`recorded_by`)
    REFERENCES `captain_kai_sod_db`.`users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cash_transactions_sale_payment`
    FOREIGN KEY (`sale_payment_id`)
    REFERENCES `captain_kai_sod_db`.`sale_payments` (`sale_payment_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cash_transactions_credit_payment`
    FOREIGN KEY (`credit_payment_id`)
    REFERENCES `captain_kai_sod_db`.`credit_payments` (`credit_payment_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
